# Generated by Django 4.2.7 on 2023-11-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rol', models.CharField(max_length=50)),
                ('permite_crear', models.BooleanField(default=False)),
                ('permite_editar', models.BooleanField(default=False)),
                ('permite_eliminar', models.BooleanField(default=False)),
                ('permite_invitar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.rol')),
            ],
        ),
    ]
